services:
  ruleta-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: ruleta-d3
